# Generated by Django 3.2 on 2021-07-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterKihon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHARCTER_CD', models.CharField(max_length=8)),
                ('CHARACTER_NAME', models.CharField(max_length=30)),
                ('CHARACTER_KIND', models.CharField(max_length=2)),
                ('CHARACTER_BIRTH', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterLooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHARCTER_CD', models.CharField(max_length=8)),
                ('CHARACTER_HEIGHT', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('CHARACTER_WEIGHT', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
    ]
