# Generated by Django 3.2 on 2021-07-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterkihon',
            old_name='CHARCTER_CD',
            new_name='CHARACTER_CD',
        ),
    ]
