# Generated by Django 3.2 on 2021-07-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0002_rename_charcter_cd_characterkihon_character_cd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterlooks',
            old_name='CHARCTER_CD',
            new_name='CHARACTER_CD',
        ),
    ]
